// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.15.5
// source: api/msg_api/msg_api.proto

package msg_api

import (
	protocol "github.com/openlinkz/openlink/api/protocol"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BizMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid      string             `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Platform protocol.Platform  `protobuf:"varint,2,opt,name=platform,proto3,enum=api.msg.protocol.Platform" json:"platform,omitempty"`
	Protocol *protocol.Protocol `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
}

func (x *BizMsg) Reset() {
	*x = BizMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_msg_api_msg_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BizMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BizMsg) ProtoMessage() {}

func (x *BizMsg) ProtoReflect() protoreflect.Message {
	mi := &file_api_msg_api_msg_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BizMsg.ProtoReflect.Descriptor instead.
func (*BizMsg) Descriptor() ([]byte, []int) {
	return file_api_msg_api_msg_api_proto_rawDescGZIP(), []int{0}
}

func (x *BizMsg) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *BizMsg) GetPlatform() protocol.Platform {
	if x != nil {
		return x.Platform
	}
	return protocol.Platform(0)
}

func (x *BizMsg) GetProtocol() *protocol.Protocol {
	if x != nil {
		return x.Protocol
	}
	return nil
}

type PushBizMsgReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SuccessCount int64 `protobuf:"varint,1,opt,name=successCount,proto3" json:"successCount,omitempty"` // 推送成功用户数量
}

func (x *PushBizMsgReply) Reset() {
	*x = PushBizMsgReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_msg_api_msg_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushBizMsgReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushBizMsgReply) ProtoMessage() {}

func (x *PushBizMsgReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_msg_api_msg_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushBizMsgReply.ProtoReflect.Descriptor instead.
func (*PushBizMsgReply) Descriptor() ([]byte, []int) {
	return file_api_msg_api_msg_api_proto_rawDescGZIP(), []int{1}
}

func (x *PushBizMsgReply) GetSuccessCount() int64 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

var File_api_msg_api_msg_api_proto protoreflect.FileDescriptor

var file_api_msg_api_msg_api_proto_rawDesc = []byte{
	0x0a, 0x19, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x73, 0x67, 0x5f, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x73,
	0x67, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x61, 0x70, 0x69,
	0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x61, 0x70, 0x69, 0x1a, 0x1b, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8a, 0x01, 0x0a, 0x06, 0x42, 0x69, 0x7a, 0x4d, 0x73, 0x67,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75,
	0x69, 0x64, 0x12, 0x36, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x52, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x36, 0x0a, 0x08, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x22, 0x35, 0x0a, 0x0f, 0x50, 0x75, 0x73, 0x68, 0x42, 0x69, 0x7a, 0x4d, 0x73, 0x67,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x32, 0x4f, 0x0a, 0x0d, 0x4d, 0x73, 0x67,
	0x41, 0x50, 0x49, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3e, 0x0a, 0x07, 0x50, 0x75,
	0x73, 0x68, 0x4d, 0x73, 0x67, 0x12, 0x13, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x73, 0x67, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x42, 0x69, 0x7a, 0x4d, 0x73, 0x67, 0x1a, 0x1c, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x42, 0x69, 0x7a,
	0x4d, 0x73, 0x67, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x6c, 0x69, 0x6e,
	0x6b, 0x7a, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x6c, 0x69, 0x6e, 0x6b, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x6d, 0x73, 0x67, 0x5f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_msg_api_msg_api_proto_rawDescOnce sync.Once
	file_api_msg_api_msg_api_proto_rawDescData = file_api_msg_api_msg_api_proto_rawDesc
)

func file_api_msg_api_msg_api_proto_rawDescGZIP() []byte {
	file_api_msg_api_msg_api_proto_rawDescOnce.Do(func() {
		file_api_msg_api_msg_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_msg_api_msg_api_proto_rawDescData)
	})
	return file_api_msg_api_msg_api_proto_rawDescData
}

var file_api_msg_api_msg_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_msg_api_msg_api_proto_goTypes = []interface{}{
	(*BizMsg)(nil),            // 0: api.msg.api.BizMsg
	(*PushBizMsgReply)(nil),   // 1: api.msg.api.PushBizMsgReply
	(protocol.Platform)(0),    // 2: api.msg.protocol.Platform
	(*protocol.Protocol)(nil), // 3: api.msg.protocol.Protocol
}
var file_api_msg_api_msg_api_proto_depIdxs = []int32{
	2, // 0: api.msg.api.BizMsg.platform:type_name -> api.msg.protocol.Platform
	3, // 1: api.msg.api.BizMsg.protocol:type_name -> api.msg.protocol.Protocol
	0, // 2: api.msg.api.MsgAPIService.PushMsg:input_type -> api.msg.api.BizMsg
	1, // 3: api.msg.api.MsgAPIService.PushMsg:output_type -> api.msg.api.PushBizMsgReply
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_msg_api_msg_api_proto_init() }
func file_api_msg_api_msg_api_proto_init() {
	if File_api_msg_api_msg_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_msg_api_msg_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BizMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_msg_api_msg_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushBizMsgReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_msg_api_msg_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_msg_api_msg_api_proto_goTypes,
		DependencyIndexes: file_api_msg_api_msg_api_proto_depIdxs,
		MessageInfos:      file_api_msg_api_msg_api_proto_msgTypes,
	}.Build()
	File_api_msg_api_msg_api_proto = out.File
	file_api_msg_api_msg_api_proto_rawDesc = nil
	file_api_msg_api_msg_api_proto_goTypes = nil
	file_api_msg_api_msg_api_proto_depIdxs = nil
}
