server:
  http:
    addr: :28080
    timeout: 600s
  grpc:
    addr: :28081
    timeout: 600s
client:
  wsAPI:
    addr: discovery:///msg_api
    timeout: 1s
    insecure: true
registry:
  etcd:
    addr: localhost:2379
    dialTimeout: 3s