server:
  http:
    addr: :18080
    timeout: 600s
  grpc:
    addr: :18081
    timeout: 600s
registry:
  etcd:
    addr: localhost:2379
    dialTimeout: 3s
data:
  redis:
    addr: localhost:6379
    db: 0
    password: root
  kafka:
    addrs:
      - localhost:9092

