// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/openlinkz/openlink/app/msg-api/internal/biz"
	"github.com/openlinkz/openlink/app/msg-api/internal/config"
	"github.com/openlinkz/openlink/app/msg-api/internal/data"
	"github.com/openlinkz/openlink/app/msg-api/internal/server"
	"github.com/openlinkz/openlink/app/msg-api/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

func initApp(configServer *config.Server, registry *config.Registry, logger log.Logger) (*kratos.App, error) {
	msgRepo := data.NewMsgRepo()
	msgExchangeBiz := biz.NewMsgExchangeBiz(msgRepo)
	userStatusRepo := data.NewUserStatusRepo()
	userStatusBiz := biz.NewUserStatusBiz(userStatusRepo)
	msgExchangeService := service.NewMsgExchangeService(msgExchangeBiz, userStatusBiz)
	v := server.NewServers(configServer, msgExchangeService)
	registrar := server.NewRegistry(registry)
	app := newApp(logger, v, registrar)
	return app, nil
}
